### ISSUE TITLE
Shavit_GetWRName incorrect identification of the player's name

### ISSUE THREAD

**Issue by Lime18** [shavitush/bhoptimer#377]
On most maps it works correctly, but it also happens :(
![wr1](https://user-images.githubusercontent.com/29817277/27762742-675ee23a-5e80-11e7-9aa7-5a9fefc095bf.png)
![wr2](https://user-images.githubusercontent.com/29817277/27762743-67618da0-5e80-11e7-8cd7-da2e744dca7e.png)

**Comment by Nickelony** [comment]
Yup, same thing here.

**Comment by shavitush** [comment]
In `shavit-wr.sp`, can you let me know if editing line 376, from this:

    FormatEx(sQuery, 512, "SELECT p.style, p.id, s.time, u.name FROM %splayertimes p JOIN(SELECT style, MIN(time) time FROM %splayertimes WHERE map = '%s' GROUP BY style) s ON p.style = s.style AND p.time = s.time JOIN %susers u ON p.auth = u.auth;", gS_MySQLPrefix, gS_MySQLPrefix, gS_Map, gS_MySQLPrefix);

To this:

    FormatEx(sQuery, 512, "SELECT p.style, p.id, s.time, u.name FROM %splayertimes p JOIN(SELECT style, MIN(time) time FROM %splayertimes WHERE map = '%s' GROUP BY style) s ON p.style = s.style AND p.time = s.time JOIN %susers u ON p.auth = u.auth GROUP BY p.style;", gS_MySQLPrefix, gS_MySQLPrefix, gS_Map, gS_MySQLPrefix);

Solves the issue?

**Comment by Lime18** [comment]
It looks like it solves the problem, thanks)

**Comment by shavitush** [comment]
You're welcomed))))))))

**Comment by Lime18** [comment]
The problem still exists ...
![1](https://user-images.githubusercontent.com/29817277/28132921-f8fa7370-6746-11e7-8939-f06c174bf8e0.png)
![2](https://user-images.githubusercontent.com/29817277/28132922-f8fe57e2-6746-11e7-9b4e-544c2e7c337a.png)

**Comment by shavitush** [comment]
I have NO IDEA why this is happening. Help is appreciated.

**Comment by Lime18** [comment]
Sent you a mysql backup to alliedmods, maybe this will help you.

**Comment by shavitush** [comment]
May I know which map that happened on?

**Comment by Lime18** [comment]
I sent everything to you on forums alliedmods! There are quite a few such maps, one of them http://steamcommunity.com/sharedfiles/filedetails/?id=943669555

**Comment by strafe** [comment]
@shavitush can't you do a query that's almost the same as the style-specific WR menu one and use limit to get just the WR data?

**Comment by Lime18** [comment]
Map: http://steamcommunity.com/sharedfiles/filedetails/?id=742357438
`shavit-wr.sp` line 376

> SELECT p.style, p.id, s.time, u.name FROM %splayertimes p JOIN(SELECT style, MIN(time) time FROM %splayertimes WHERE map = '%s' GROUP BY style) s ON p.style = s.style AND p.time = s.time JOIN %susers u ON p.auth = u.auth **GROUP BY p.style**;

![1](https://user-images.githubusercontent.com/29817277/28239578-052c9744-6978-11e7-8ac9-b64faaad6bd1.png)

> SELECT p.style, p.id, s.time, u.name FROM %splayertimes p JOIN(SELECT style, MIN(time) time FROM %splayertimes WHERE map = '%s' GROUP BY style) s ON p.style = s.style AND p.time = s.time JOIN %susers u ON p.auth = u.auth;

![2](https://user-images.githubusercontent.com/29817277/28239579-0e25eae4-6978-11e7-82d6-56be09b5052f.png)

Map: https://steamcommunity.com/sharedfiles/filedetails/?id=972991913

> SELECT p.style, p.id, s.time, u.name FROM %splayertimes p JOIN(SELECT style, MIN(time) time FROM %splayertimes WHERE map = '%s' GROUP BY style) s ON p.style = s.style AND p.time = s.time JOIN %susers u ON p.auth = u.auth **GROUP BY p.style**;

![3](https://user-images.githubusercontent.com/29817277/28239583-22c4ce70-6978-11e7-94e0-01ff5c655537.png)

> SELECT p.style, p.id, s.time, u.name FROM %splayertimes p JOIN(SELECT style, MIN(time) time FROM %splayertimes WHERE map = '%s' GROUP BY style) s ON p.style = s.style AND p.time = s.time JOIN %susers u ON p.auth = u.auth;

![4](https://user-images.githubusercontent.com/29817277/28239585-27d78cea-6978-11e7-909b-c6105982bb48.png)

**Comment by strafe** [comment]
@Lime18 could you upload your SQL file here?

**Comment by Technoblazed** [comment]
^

**Comment by Lime18** [comment]
As I understood the problem in this
![6](https://user-images.githubusercontent.com/29817277/28241007-942203dc-6994-11e7-9959-177c6cbec20b.png)

![5](https://user-images.githubusercontent.com/29817277/28241006-91c1b006-6994-11e7-8599-fe5ba5dbd45b.png)

**Comment by Technoblazed** [comment]
So the actual menu version, is using an `ORDER BY` clause, to order by time. It looks like the one in the top right is using the most recent time for the value of `MIN`.

**Comment by shavitush** [comment]
> Although on another note, the top screenshot you sent, why does the second one, which was a run completed before the 1st ID, have a higher date unix timestamp?

Probably someone improved their record.

**Comment by Technoblazed** [comment]
Ah, does it just run an update query for that?

**Comment by shavitush** [comment]
Yes! I think that you have a point about the `MIN()` being correct but the name itself being wrong. I'll look into it, I'm not sure why it's fine sometimes but sometimes it isn't though..

**Comment by Technoblazed** [comment]
Let me message another SQL nerd.

**Comment by Technoblazed** [comment]
@shavitush Could it also be that the actual WR menu, just needs an additional sort on the `time` field? Perhaps adding a `timestamp ASC` as well?

**Comment by shavitush** [comment]
But wait.. the issue is with the top-left HUD, not with the WR menu entry!

**Comment by Technoblazed** [comment]
I don't understand how that's the issue?

**Comment by shavitush** [comment]
@Lime18 can you check if results from the top-left HUD are identical to the first WR entry after applying 3b2cf99?

**Comment by Lime18** [comment]
@shavitush problem still exists.

**Comment by Lime18** [comment]
@shavitush i do not know if this is correct, but it solved the problem.

> SELECT p.style, p.id, s.time, u.name FROM %splayertimes p JOIN(SELECT style, MIN(time) time FROM %splayertimes WHERE map = '%s' GROUP BY style) s ON p.style = s.style AND p.time = s.time JOIN %susers u ON p.auth = u.auth GROUP BY p.style, **date ASC**;

**Comment by shavitush** [comment]
@Lime18 is your problem solved with this solution for both maps?

**Comment by shavitush** [comment]
Try this instead, I believe that it's the proper fix - I tried it on 15 maps in my server and everything seems good.

```sp
FormatEx(sQuery, 512, "SELECT p.style, p.id, s.time, u.name FROM %splayertimes p JOIN(SELECT style, MIN(time) time, map FROM %splayertimes WHERE map = '%s' GROUP BY style) s ON p.style = s.style AND p.time = s.time AND p.map = s.map JOIN %susers u ON p.auth = u.auth GROUP BY p.style;", gS_MySQLPrefix, gS_MySQLPrefix, gS_Map, gS_MySQLPrefix);```

**Comment by Lime18** [comment]
@shavitush yeah, it works :)
![fix1](https://user-images.githubusercontent.com/29817277/28247841-ad2144d0-6a41-11e7-8222-d4dc3013a207.png)
![fix2](https://user-images.githubusercontent.com/29817277/28247842-b06f2ab2-6a41-11e7-996c-8d253f159aef.png)

**Comment by shavitush** [comment]
For those wondering, the query didn't check for maps too. So if someone had.. 59:10.002 on bhop_badges2 and 59:10.002 seconds on bhop_alvo2, MySQL would prefer one of the two and therefore mix up the names. Unless it's one player that set both records, but that'd never happen in a real world situation.

**Comment by Technoblazed** [comment]
I still don't agree with this, it's basically giving the second person to achieve the time, the first place position?

**Comment by shavitush** [comment]
@Technoblazed no, considering MySQL's MIN() picks the row that was inserted to the table first.

**Comment by Technoblazed** [comment]
But it's doing an update query, so the first record might not have always been the first person to get that time, more rather just played the map first

**Comment by shavitush** [comment]
Fair point. what about this, @Technoblazed?

```sp
FormatEx(sQuery, 512, "SELECT p.style, p.id, TRUNCATE(LEAST(s.time, p.time), 3), u.name FROM %splayertimes p JOIN(SELECT style, MIN(time) time, map FROM %splayertimes WHERE map = '%s' GROUP BY style ORDER BY date ASC) s ON p.style = s.style AND p.time = s.time AND p.map = s.map JOIN %susers u ON p.auth = u.auth GROUP BY p.style ORDER BY date ASC;", gS_MySQLPrefix, gS_MySQLPrefix, gS_Map, gS_MySQLPrefix);
```

"Just a little bit long", but should do the job.

**Comment by Technoblazed** [comment]
That shoulddddd do it
