### ISSUE TITLE
[BUG] Every map has WR: 28.500() (without even adding zones in it)

### ISSUE THREAD

**Issue by Cruze03** [shavitush/bhoptimer#691]
http://prntscr.com/ldunv3

**Comment by shavitush** [comment]
do you have anything in error logs?

**Comment by Cruze03** [comment]
L 11/03/2018 - 08:14:38: Error log file session closed.
L 11/03/2018 - 08:14:40: SourceMod error session started
L 11/03/2018 - 08:14:40: Info (map "workshop/444836329/bhop_christmas") (file "errors_20181103.log")
L 11/03/2018 - 08:14:40: [shavit-wr.smx] Timer (WR cache update) SQL query failed. Reason: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'shavit.playertimes.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
L 11/03/2018 - 08:14:45: [shavit-core.smx] Timer error! Failed to insert "♚Cr[U]zE♚"'s data to the table. Reason: Incorrect string value: '\xE2\x99\x9ACr[...' for column 'name' at row 1
L 11/03/2018 - 08:14:46: [shavit-rankings.smx] Timer (rankings, update player rank) error! Reason: In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'p.points'; this is incompatible with sql_mode=only_full_group_by
L 11/03/2018 - 08:15:43: Error log file session closed.
L 11/03/2018 - 08:15:46: SourceMod error session started
L 11/03/2018 - 08:15:46: Info (map "workshop/444836329/bhop_christmas") (file "errors_20181103.log")
L 11/03/2018 - 08:15:46: [shavit-wr.smx] Timer (WR cache update) SQL query failed. Reason: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'shavit.playertimes.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
L 11/03/2018 - 08:15:49: [shavit-core.smx] Timer error! Failed to insert "♚Cr[U]zE♚"'s data to the table. Reason: Incorrect string value: '\xE2\x99\x9ACr[...' for column 'name' at row 1
L 11/03/2018 - 08:15:50: [shavit-rankings.smx] Timer (rankings, update player rank) error! Reason: In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'p.points'; this is incompatible with sql_mode=only_full_group_by


MYSQL

**Comment by Cruze03** [comment]
It's because of my symbol in name maybe?

**Comment by Cruze03** [comment]
Okay, let me test!

**Comment by Cruze03** [comment]
Okay, now that bug(28.500) is fixed but my name is not coming in hud: http://prntscr.com/lduym5

**Comment by shavitush** [comment]
should be fixed after a map restart as you just applied this fix

**Comment by Cruze03** [comment]
Changed map: No change.
Restarted Server: Now nothing is appearing. No WR hud

**Comment by shavitush** [comment]
anything new in your error logs now?

**Comment by Cruze03** [comment]
[CODE]L 11/03/2018 - 08:54:10: SourceMod error session started
L 11/03/2018 - 08:54:10: Info (map "workshop/1195640353/bhop_woodenxd") (file "errors_20181103.log")
L 11/03/2018 - 08:54:10: [shavit-wr.smx] Timer (WR cache update) SQL query failed. Reason: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'shavit.playertimes.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
L 11/03/2018 - 08:54:10: [shavit-wr.smx] Timer (WR cache update) SQL query failed. Reason: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'shavit.playertimes.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
L 11/03/2018 - 08:54:13: Error log file session closed.
L 11/03/2018 - 08:54:15: SourceMod error session started
L 11/03/2018 - 08:54:15: Info (map "workshop/1195640353/bhop_woodenxd") (file "errors_20181103.log")
L 11/03/2018 - 08:54:15: [shavit-wr.smx] Timer (WR cache update) SQL query failed. Reason: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'shavit.playertimes.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
L 11/03/2018 - 08:54:26: [shavit-core.smx] Timer error! Failed to insert "♚Cr[U]zE♚"'s data to the table. Reason: Incorrect string value: '\xE2\x99\x9ACr[...' for column 'name' at row 1
L 11/03/2018 - 08:54:26: [shavit-rankings.smx] Timer (rankings, update player rank) error! Reason: In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'p.points'; this is incompatible with sql_mode=only_full_group_by
L 11/03/2018 - 08:55:05: Error log file session closed.
L 11/03/2018 - 08:55:08: SourceMod error session started
L 11/03/2018 - 08:55:08: Info (map "workshop/444836329/bhop_christmas") (file "errors_20181103.log")
L 11/03/2018 - 08:55:08: [shavit-wr.smx] Timer (WR cache update) SQL query failed. Reason: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'shavit.playertimes.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
L 11/03/2018 - 08:55:19: [shavit-core.smx] Timer error! Failed to insert "♚Cr[U]zE♚"'s data to the table. Reason: Incorrect string value: '\xE2\x99\x9ACr[...' for column 'name' at row 1
L 11/03/2018 - 08:55:19: [shavit-rankings.smx] Timer (rankings, update player rank) error! Reason: In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'p.points'; this is incompatible with sql_mode=only_full_group_by
L 11/03/2018 - 09:00:02: Error log file session closed.
L 11/03/2018 - 09:00:07: SourceMod error session started
L 11/03/2018 - 09:00:07: Info (map "workshop/1195611105/bhop_cobblestone_rg1") (file "errors_20181103.log")
L 11/03/2018 - 09:00:07: [shavit-wr.smx] Timer (WR cache update) SQL query failed. Reason: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'shavit.playertimes.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
L 11/03/2018 - 09:00:10: [shavit-wr.smx] Timer (WR cache update) SQL query failed. Reason: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'shavit.playertimes.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
L 11/03/2018 - 09:00:28: [shavit-core.smx] Timer error! Failed to insert "♚Cr[U]zE♚"'s data to the table. Reason: Incorrect string value: '\xE2\x99\x9ACr[...' for column 'name' at row 1
L 11/03/2018 - 09:00:28: [shavit-rankings.smx] Timer (rankings, update player rank) error! Reason: In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'p.points'; this is incompatible with sql_mode=only_full_group_by
L 11/03/2018 - 09:02:44: Error log file session closed.
L 11/03/2018 - 09:02:46: SourceMod error session started
L 11/03/2018 - 09:02:46: Info (map "workshop/444836329/bhop_christmas") (file "errors_20181103.log")
L 11/03/2018 - 09:02:46: [shavit-wr.smx] Timer (WR cache update) SQL query failed. Reason: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'shavit.playertimes.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
L 11/03/2018 - 09:02:56: [shavit-core.smx] Timer error! Failed to insert "♚Cr[U]zE♚"'s data to the table. Reason: Incorrect string value: '\xE2\x99\x9ACr[...' for column 'name' at row 1
L 11/03/2018 - 09:02:56: [shavit-rankings.smx] Timer (rankings, update player rank) error! Reason: In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'p.points'; this is incompatible with sql_mode=only_full_group_by
[/CODE]

**Comment by Cruze03** [comment]
Updated to sourcemod 1.10 - build 6354. Still the same.. http://prntscr.com/ldva47
L 11/03/2018 - 09:27:41: Error log file session closed.
L 11/03/2018 - 09:27:44: SourceMod error session started
L 11/03/2018 - 09:27:44: Info (map "workshop/1195606990/bhop_anyyy") (file "/home/container/csgo/addons/sourcemod/logs/errors_20181103.log")
L 11/03/2018 - 09:27:44: [shavit-wr.smx] Timer (WR cache update) SQL query failed. Reason: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'shavit.playertimes.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
L 11/03/2018 - 09:27:54: [shavit-core.smx] Timer error! Failed to insert "♚Cr[U]zE♚"'s data to the table. Reason: Incorrect string value: '\xE2\x99\x9ACr[...' for column 'name' at row 1
L 11/03/2018 - 09:27:54: [shavit-rankings.smx] Timer (rankings, update player rank) error! Reason: In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'p.points'; this is incompatible with sql_mode=only_full_group_by
L 11/03/2018 - 09:28:48: [shavit-wr.smx] Timer (WR cache update) SQL query failed. Reason: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'shavit.playertimes.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by shavitush** [comment]
set the collation of `names` in your `users` table to `utf8mb4_unicode_ci` and see if the first error fixes
for the second one, i'll push a fix soon

**Comment by Cruze03** [comment]
Okay! Thanks!!

**Comment by Cruze03** [comment]
L 11/03/2018 - 11:36:13: Error log file session closed.
L 11/03/2018 - 11:36:16: SourceMod error session started
L 11/03/2018 - 11:36:16: Info (map "workshop/1195640353/bhop_woodenxd") (file "/home/container/csgo/addons/sourcemod/logs/errors_20181103.log")
L 11/03/2018 - 11:36:16: [shavit-wr.smx] Timer (WR cache update) SQL query failed. Reason: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'shavit3.playertimes.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
L 11/03/2018 - 11:36:28: [shavit-rankings.smx] Timer (rankings, update player rank) error! Reason: In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'p.points'; this is incompatible with sql_mode=only_full_group_by
L 11/03/2018 - 11:36:57: Error log file session closed.
L 11/03/2018 - 11:37:00: SourceMod error session started
L 11/03/2018 - 11:37:00: Info (map "workshop/1195606990/bhop_anyyy") (file "/home/container/csgo/addons/sourcemod/logs/errors_20181103.log")
L 11/03/2018 - 11:37:00: [shavit-wr.smx] Timer (WR cache update) SQL query failed. Reason: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'shavit3.playertimes.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
L 11/03/2018 - 11:37:04: [shavit-rankings.smx] Timer (rankings, update player rank) error! Reason: In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'p.points'; this is incompatible with sql_mode=only_full_group_by

Still the same :(
Updated plugin. Map Changed. Restarted Server..

**Comment by shavitush** [comment]
you didn't compile the goddamn new plugin

**Comment by shavitush** [comment]
just change your sql_mode setting, i'm not rewriting every query in the plugin
